[cosmic-ray]
module-path = "/Users/jan/Documents/Git/categorical-encoding/category_encoders"
python-version = "3.7"
timeout = 1200.0
excluded-modules = []
test-command = "/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -m unittest discover tests"

[cosmic-ray.execution-engine]
name = "local"

[cosmic-ray.cloning]
method = "copy"
commands = []
